# Generated by Django 4.2.2 on 2023-06-15 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('b_type', models.CharField(choices=[('Resource', 'Resource'), ('Military', 'Military')], max_length=50, verbose_name='b_type')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='level')),
                ('construction_time', models.JSONField(verbose_name='construction_time')),
                ('population', models.JSONField(verbose_name='population')),
                ('resource_generation_rate', models.JSONField(verbose_name='resource_generation_rate')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='population')),
                ('granary_capacity', models.PositiveIntegerField(default=800, verbose_name='granary_capacity')),
                ('cranny_capacity', models.PositiveIntegerField(default=800, verbose_name='cranny_capacity')),
                ('wood_amount', models.PositiveIntegerField(default=750, verbose_name='wood_amount')),
                ('iron_amount', models.PositiveIntegerField(default=750, verbose_name='iron_amount')),
                ('clay_amount', models.PositiveIntegerField(default=750, verbose_name='clay_amount')),
                ('crop_amount', models.PositiveIntegerField(default=750, verbose_name='crop_amount')),
                ('buildings', models.ManyToManyField(related_name='villages', to='travian.building', verbose_name='buildings')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village', to=settings.AUTH_USER_MODEL, verbose_name='player')),
            ],
            options={
                'verbose_name': 'village',
                'verbose_name_plural': 'villages',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(choices=[('Wood', 'Wood'), ('Clay', 'Clay'), ('Iron', 'Iron'), ('Crop', 'Crop')], max_length=50, verbose_name='r_type')),
                ('generation_rate', models.PositiveIntegerField(verbose_name='generation_rate')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='travian.village', verbose_name='village')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='travian.village', verbose_name='village'),
        ),
    ]
