# Generated by Django 4.2.2 on 2023-06-16 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('b_type', models.CharField(choices=[('Resource', 'Resource'), ('Military', 'Military')], max_length=50, verbose_name='b_type')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8'), (9, 'Level 9'), (10, 'Level 10')], default=1, verbose_name='level')),
                ('construction_time', models.JSONField(verbose_name='construction_time')),
                ('population', models.JSONField(verbose_name='population')),
                ('resource_generation_rate', models.JSONField(verbose_name='resource_generation_rate')),
                ('building_cost', models.JSONField(verbose_name='building_cost')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_rate', models.PositiveIntegerField(default=0, verbose_name='generation_rate')),
                ('building', models.ManyToManyField(blank=True, related_name='resources', to='travian.building', verbose_name='buildings')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('population', models.PositiveIntegerField(default=0, verbose_name='population')),
                ('granary_capacity', models.PositiveIntegerField(default=800, verbose_name='granary_capacity')),
                ('cranny_capacity', models.PositiveIntegerField(default=800, verbose_name='cranny_capacity')),
                ('wood_amount', models.PositiveIntegerField(default=750, verbose_name='wood_amount')),
                ('iron_amount', models.PositiveIntegerField(default=750, verbose_name='iron_amount')),
                ('clay_amount', models.PositiveIntegerField(default=750, verbose_name='clay_amount')),
                ('crop_amount', models.PositiveIntegerField(default=750, verbose_name='crop_amount')),
            ],
            options={
                'verbose_name': 'village',
                'verbose_name_plural': 'villages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VillageBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level', models.IntegerField(default=1)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_villages', to='travian.building')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_resources', to='travian.resource')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_buildings', to='travian.village')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='village',
            name='building',
            field=models.ManyToManyField(blank=True, related_name='buildings', through='travian.VillageBuilding', to='travian.building', verbose_name='buildings'),
        ),
        migrations.AddField(
            model_name='village',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village', to=settings.AUTH_USER_MODEL, verbose_name='player'),
        ),
        migrations.AddField(
            model_name='resource',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='travian.village', verbose_name='village'),
        ),
    ]
