# Generated by Django 4.2.2 on 2023-06-19 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='clay_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10, verbose_name='clay_amount'),
        ),
        migrations.AlterField(
            model_name='village',
            name='crop_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10, verbose_name='crop_amount'),
        ),
        migrations.AlterField(
            model_name='village',
            name='iron_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10, verbose_name='iron_amount'),
        ),
        migrations.AlterField(
            model_name='village',
            name='wood_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=10, verbose_name='wood_amount'),
        ),
    ]
