# Generated by Django 4.2.2 on 2023-06-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='travian.village', verbose_name='village'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='travian.village', verbose_name='village'),
        ),
    ]
