# Generated by Django 4.2.2 on 2023-06-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='building',
            field=models.ManyToManyField(blank=True, through='travian.VillageBuilding', to='travian.building', verbose_name='buildings'),
        ),
    ]
