# Generated by Django 4.2.2 on 2023-06-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0002_alter_building_village_alter_resource_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='buildings',
            field=models.ManyToManyField(blank=True, null=True, related_name='villages', to='travian.building', verbose_name='buildings'),
        ),
    ]
