# Generated by Django 4.2.2 on 2023-06-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0003_alter_village_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagebuilding',
            name='quantity',
        ),
    ]
