# Generated by Django 4.2.2 on 2023-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0003_alter_village_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='generation_rate',
            field=models.PositiveIntegerField(default=0, verbose_name='generation_rate'),
        ),
        migrations.AlterField(
            model_name='village',
            name='buildings',
            field=models.ManyToManyField(blank=True, related_name='villages', to='travian.building', verbose_name='buildings'),
        ),
    ]
