# Generated by Django 4.2.2 on 2023-06-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0004_building_extra_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='b_type',
            field=models.CharField(choices=[('Resource', 'Resource'), ('Military', 'Military'), ('Infrastructure', 'Infrastructure')], max_length=50, verbose_name='b_type'),
        ),
        migrations.AlterField(
            model_name='villagebuilding',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_resources', to='travian.resource'),
        ),
    ]
