# Generated by Django 4.2.2 on 2023-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0004_remove_villagebuilding_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagebuilding',
            name='name',
            field=models.CharField(default=0, max_length=100, verbose_name='name'),
        ),
    ]
