# Generated by Django 4.2.2 on 2023-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0005_villagebuilding_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagebuilding',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
