# Generated by Django 4.2.2 on 2023-06-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0006_alter_villagebuilding_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagebuilding',
            name='building_instance_id',
            field=models.IntegerField(default=0),
        ),
    ]
