# Generated by Django 4.2.2 on 2023-06-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0006_alter_building_building_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagebuilding',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_resources', to='travian.resource'),
        ),
    ]
