# Generated by Django 4.2.2 on 2023-06-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0007_alter_villagebuilding_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_cost',
            field=models.JSONField(verbose_name='building_cost'),
        ),
    ]
