# Generated by Django 4.2.2 on 2023-06-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0008_alter_building_building_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('attack', models.PositiveIntegerField(default=0, verbose_name='attack')),
                ('defense', models.PositiveIntegerField(default=0, verbose_name='defense')),
                ('carrying_capacity', models.PositiveIntegerField(default=0, verbose_name='carrying_capacityi')),
                ('crop_consumption', models.PositiveIntegerField(default=0, verbose_name='crop_consumption')),
                ('construction_time', models.JSONField(blank=True, null=True, verbose_name='construction_time')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troops', to='travian.building', verbose_name='building')),
            ],
            options={
                'verbose_name': 'troop',
                'verbose_name_plural': 'troops',
            },
        ),
        migrations.CreateModel(
            name='VillageTroop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('troop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_troops', to='travian.troop')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_troops', to='travian.village')),
            ],
            options={
                'verbose_name': 'villageTroop',
                'verbose_name_plural': 'villageTroops',
            },
        ),
    ]
