# Generated by Django 4.2.2 on 2023-06-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0008_alter_villagebuilding_building_instance_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='villagebuilding',
            unique_together=set(),
        ),
    ]
