# Generated by Django 4.2.2 on 2023-06-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0009_troop_villagetroop'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='construction_cost',
            field=models.JSONField(blank=True, null=True, verbose_name='construction_cost'),
        ),
    ]
