# Generated by Django 4.2.2 on 2023-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0009_alter_villagebuilding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagebuilding',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
