# Generated by Django 4.2.2 on 2023-06-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0010_villagebuilding_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagebuilding',
            name='building_instance_id',
        ),
    ]
