# Generated by Django 4.2.2 on 2023-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0011_remove_troop_building_troop_t_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='troop',
            name='t_type',
            field=models.CharField(blank=True, choices=[('Infantry', 'Infantry'), ('Cavalry', 'Cavalry')], max_length=50, null=True, verbose_name='t_type'),
        ),
    ]
