# Generated by Django 4.2.2 on 2023-06-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0012_alter_troop_t_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagetroop',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
