# Generated by Django 4.2.2 on 2023-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0013_villagetroop_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='troop',
            name='cavalry_defense',
            field=models.PositiveIntegerField(default=0, verbose_name='cavalry_defense'),
        ),
    ]
