# Generated by Django 4.2.2 on 2023-06-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0014_troop_cavalry_defense'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='building',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='building_pictures', verbose_name='picture'),
        ),
    ]
