# Generated by Django 4.2.2 on 2023-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0016_alter_building_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
    ]
