# Generated by Django 4.2.2 on 2023-06-22 21:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('travian', '0018_troop_description_troop_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
    ]
